apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-demo
resources:
  - k8s/namespace.yaml
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/presync-verify.yaml

commonLabels:
  app.kubernetes.io/part-of: gitops-secure-demo
